// app/components/base/Pagination.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ChevronRight } from 'lucide-vue-next'

const props = defineProps<{ page: number; total: number; perPage: number }>()
const emit = defineEmits<{ change: [number] }>()

const pages = computed(() => Math.ceil(props.total / props.perPage))
const from = computed(() => (props.page - 1) * props.perPage + 1)
const to = computed(() => Math.min(props.page * props.perPage, props.total))
const nums = computed(() => Array.from({ length: Math.min(pages.value, 5) }, (_, i) => i + 1))
const gradient = { background: 'linear-gradient(135deg, hsl(var(--primary-h) var(--primary-s) 60%), hsl(var(--primary-h) var(--primary-s) 42%))' }
</script>

<template>
  <div class="flex items-center justify-between px-5 py-3 border-t border-border/70 text-[12px] text-muted-foreground">
    <span>Hiển thị <span class="font-semibold text-foreground tabular-nums">{{ from }}-{{ to }}</span> trên <span class="font-semibold text-foreground tabular-nums">{{ total }}</span></span>
    <div class="flex items-center gap-1">
      <button :disabled="page <= 1" class="h-7 px-2 rounded-md hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed inline-flex items-center gap-1" @click="emit('change', page - 1)">
        <ChevronRight :size="11" class="rotate-180" /> Trước
      </button>
      <button v-for="p in nums" :key="p" :class="'h-7 min-w-7 px-2 rounded-md font-medium tabular-nums ' + (p === page ? 'text-white shadow-sm' : 'hover:bg-muted text-foreground')" :style="p === page ? gradient : {}" @click="emit('change', p)">{{ p }}</button>
      <span v-if="pages > 5" class="px-1">…</span>
      <button :disabled="page >= pages" class="h-7 px-2 rounded-md hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed inline-flex items-center gap-1" @click="emit('change', page + 1)">
        Sau <ChevronRight :size="11" />
      </button>
    </div>
  </div>
</template>

// design/components/pagination/Pagination.jsx
import React from 'react';

/* Micro ERP Pagination — range summary on the left, page controls on the right.
   Active page uses the accent gradient; sits on a top border (table footer). */
export function Pagination({ page, total, perPage = 10, onChange, className = '', style = {} }) {
  const pages = Math.max(1, Math.ceil(total / perPage));
  const from = total === 0 ? 0 : (page - 1) * perPage + 1;
  const to = Math.min(page * perPage, total);
  const go = (p) => { if (p >= 1 && p <= pages && onChange) onChange(p); };
  const nums = Array.from({ length: Math.min(pages, 5) }, (_, i) => i + 1);

  const ctrl = { height: 28, padding: '0 8px', borderRadius: 'var(--radius-sm)', fontSize: 12, display: 'inline-flex', alignItems: 'center', gap: 4, border: 0, background: 'transparent', cursor: 'pointer', color: 'hsl(var(--foreground))' };

  return (
    <div className={className} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 20px', borderTop: '1px solid hsl(var(--border) / 0.7)', fontSize: 12, color: 'hsl(var(--muted-foreground))', fontFamily: 'var(--font-sans)', ...style }}>
      <span>Hiển thị <b style={{ color: 'hsl(var(--foreground))', fontVariantNumeric: 'tabular-nums' }}>{from}-{to}</b> trên <b style={{ color: 'hsl(var(--foreground))', fontVariantNumeric: 'tabular-nums' }}>{total}</b></span>
      <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
        <button style={{ ...ctrl, opacity: page <= 1 ? 0.4 : 1, cursor: page <= 1 ? 'not-allowed' : 'pointer' }} disabled={page <= 1} onClick={() => go(page - 1)}>‹ Trước</button>
        {nums.map(p => (
          <button key={p} onClick={() => go(p)} style={{
            height: 28, minWidth: 28, padding: '0 8px', borderRadius: 'var(--radius-sm)', fontSize: 12, fontWeight: 500,
            fontVariantNumeric: 'tabular-nums', border: 0, cursor: 'pointer',
            background: p === page ? 'var(--grad-primary)' : 'transparent',
            color: p === page ? '#fff' : 'hsl(var(--foreground))',
            boxShadow: p === page ? 'var(--shadow-card)' : 'none',
          }}>{p}</button>
        ))}
        {pages > 5 && <span style={{ padding: '0 4px' }}>…</span>}
        <button style={{ ...ctrl, opacity: page >= pages ? 0.4 : 1, cursor: page >= pages ? 'not-allowed' : 'pointer' }} disabled={page >= pages} onClick={() => go(page + 1)}>Sau ›</button>
      </div>
    </div>
  );
}
