// design/components/stat/StatCard.jsx
import React from 'react';

/* Micro ERP StatCard — the KPI block. Big heading number, uppercase label,
   optional trend chip and accent icon tile; carries the top-right accent glow. */
const ACCENTS = {
  primary: 'hsl(var(--primary))',
  green:   'hsl(var(--success))',
  amber:   'hsl(var(--warning))',
  red:     'hsl(var(--danger))',
  violet:  'hsl(var(--violet))',
  sky:     'hsl(var(--info))',
  gray:    'hsl(220 14% 55%)',
};

export function StatCard({ label, value, sublabel, trend, icon, accent = 'primary', className = '', style = {} }) {
  const color = ACCENTS[accent] || ACCENTS.primary;
  const up = trend && trend.dir === 'up';
  return (
    <div className={className} style={{
      background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))',
      borderRadius: 'var(--radius-card)', boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.03)', padding: 20,
      backgroundImage: 'radial-gradient(ellipse 80% 60% at 100% 0%, ' + color.replace(')', ' / 0.09)') + ', transparent 70%)',
      ...style,
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
        <div>
          <span className="eyebrow">{label}</span>
          <div style={{ marginTop: 6, display: 'flex', alignItems: 'baseline', gap: 8 }}>
            <span style={{ fontSize: 34, fontWeight: 700, fontFamily: 'var(--font-heading)', color: 'hsl(var(--foreground))', lineHeight: 1, fontVariantNumeric: 'tabular-nums' }}>{value}</span>
            {trend && (
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: 2, fontSize: 12, fontWeight: 600, fontVariantNumeric: 'tabular-nums', color: up ? 'hsl(var(--success))' : 'hsl(var(--danger))' }}>
                {up ? '↑' : '↓'} {trend.value}
              </span>
            )}
          </div>
          {sublabel && <p style={{ fontSize: 12, color: 'hsl(var(--muted-foreground))', marginTop: 4 }}>{sublabel}</p>}
        </div>
        {icon && (
          <div style={{ height: 40, width: 40, borderRadius: 'var(--radius-md)', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
            background: 'linear-gradient(135deg, hsl(var(--primary-h) var(--primary-s) 60% / 0.16), hsl(var(--primary-h) var(--primary-s) 40% / 0.10))', color: 'hsl(var(--primary))' }}>
            {icon}
          </div>
        )}
      </div>
    </div>
  );
}

// app/components/home/StatCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Users, Folder, Star, TrendingUp, TrendingDown } from 'lucide-vue-next'
import Sparkline from '~/components/charts/Sparkline.vue'
import type { StatCardData } from '~/types'

const props = withDefaults(defineProps<StatCardData & { delay?: number }>(), { delay: 0 })
const ICONS: Record<string, any> = { Users, Folder, Star }
const trendUp = computed(() => props.trend?.dir === 'up')
</script>

<template>
  <div class="card-surface interactive p-5 rise flex flex-col gap-4"
       :style="{ animationDelay: delay + 'ms', backgroundImage: 'radial-gradient(ellipse 80% 60% at 100% 0%, hsl(var(--primary-h) var(--primary-s) 57% / 0.09), transparent 70%)' }">
    <div class="flex items-start justify-between gap-3">
      <div>
        <span class="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{{ label }}</span>
        <div class="mt-1.5 flex items-baseline gap-2">
          <span class="text-[34px] font-bold text-foreground font-heading tabular-nums leading-none">{{ value }}</span>
          <span v-if="trend" :class="'inline-flex items-center gap-0.5 text-[12px] font-semibold tabular-nums ' + (trendUp ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-500')">
            <component :is="trendUp ? TrendingUp : TrendingDown" :size="12" />{{ trend.value }}
          </span>
        </div>
        <p v-if="sublabel" class="text-[12px] text-muted-foreground mt-1">{{ sublabel }}</p>
      </div>
      <div class="h-10 w-10 rounded-lg flex items-center justify-center shrink-0"
           :style="{ background: 'linear-gradient(135deg, hsl(var(--primary-h) var(--primary-s) 60% / 0.16), hsl(var(--primary-h) var(--primary-s) 40% / 0.10))', color: 'hsl(var(--primary))' }">
        <component :is="ICONS[icon]" :size="18" />
      </div>
    </div>
    <div v-if="sparkData" class="text-primary -mx-1">
      <Sparkline :data="sparkData" :width="240" :height="36" stroke="currentColor" />
    </div>
    <div v-if="breakdown" class="space-y-1.5 pt-2 border-t border-border/70">
      <div v-for="(b, i) in breakdown" :key="i" class="flex items-center justify-between text-[12px]">
        <span class="text-muted-foreground">{{ b.label }}</span>
        <span class="font-semibold text-foreground tabular-nums">{{ b.value }}</span>
      </div>
    </div>
  </div>
</template>
